// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Studentsky_spravce.Data;

#nullable disable

namespace Studentsky_spravce.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260627201814_Pridani_Modelu_pro_Rozvrh")]
    partial class Pridani_Modelu_pro_Rozvrh
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.19");

            modelBuilder.Entity("Studentsky_spravce.Models.Osoba", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Jmeno")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Prijmeni")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Vek")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Osoby");

                    b.HasDiscriminator().HasValue("Osoba");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Studentsky_spravce.Models.Predmet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NazevPredmetu")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UcitelId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UcitelId");

                    b.ToTable("Predmety");
                });

            modelBuilder.Entity("Studentsky_spravce.Models.Rozvrh", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("TridaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TridaId");

                    b.ToTable("Rozvrhs");
                });

            modelBuilder.Entity("Studentsky_spravce.Models.RozvrhHodina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DenVTydnu")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Hodina")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PredmetId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RozvrhId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TridaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UcitelId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PredmetId");

                    b.HasIndex("RozvrhId");

                    b.HasIndex("TridaId");

                    b.HasIndex("UcitelId");

                    b.ToTable("Hodiny");
                });

            modelBuilder.Entity("Studentsky_spravce.Models.Trida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nazev")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("TridniUcitelId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TridniUcitelId");

                    b.ToTable("Tridy");
                });

            modelBuilder.Entity("Studentsky_spravce.Models.Znamka", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("TEXT");

                    b.Property<int>("Hodnota")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PredmetId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PredmetId");

                    b.HasIndex("StudentId");

                    b.ToTable("Znamky");
                });

            modelBuilder.Entity("Studentsky_spravce.Models.Student", b =>
                {
                    b.HasBaseType("Studentsky_spravce.Models.Osoba");

                    b.Property<int?>("TridaId")
                        .HasColumnType("INTEGER");

                    b.HasIndex("TridaId");

                    b.HasDiscriminator().HasValue("Student");
                });

            modelBuilder.Entity("Studentsky_spravce.Models.Ucitel", b =>
                {
                    b.HasBaseType("Studentsky_spravce.Models.Osoba");

                    b.HasDiscriminator().HasValue("Ucitel");
                });

            modelBuilder.Entity("Studentsky_spravce.Models.Predmet", b =>
                {
                    b.HasOne("Studentsky_spravce.Models.Ucitel", "Ucitel")
                        .WithMany()
                        .HasForeignKey("UcitelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ucitel");
                });

            modelBuilder.Entity("Studentsky_spravce.Models.Rozvrh", b =>
                {
                    b.HasOne("Studentsky_spravce.Models.Trida", "Trida")
                        .WithMany()
                        .HasForeignKey("TridaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trida");
                });

            modelBuilder.Entity("Studentsky_spravce.Models.RozvrhHodina", b =>
                {
                    b.HasOne("Studentsky_spravce.Models.Predmet", "Predmet")
                        .WithMany()
                        .HasForeignKey("PredmetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Studentsky_spravce.Models.Rozvrh", null)
                        .WithMany("Hodiny")
                        .HasForeignKey("RozvrhId");

                    b.HasOne("Studentsky_spravce.Models.Trida", "Trida")
                        .WithMany()
                        .HasForeignKey("TridaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Studentsky_spravce.Models.Ucitel", "Ucitel")
                        .WithMany()
                        .HasForeignKey("UcitelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Predmet");

                    b.Navigation("Trida");

                    b.Navigation("Ucitel");
                });

            modelBuilder.Entity("Studentsky_spravce.Models.Trida", b =>
                {
                    b.HasOne("Studentsky_spravce.Models.Ucitel", "TridniUcitel")
                        .WithMany()
                        .HasForeignKey("TridniUcitelId");

                    b.Navigation("TridniUcitel");
                });

            modelBuilder.Entity("Studentsky_spravce.Models.Znamka", b =>
                {
                    b.HasOne("Studentsky_spravce.Models.Predmet", "Predmet")
                        .WithMany()
                        .HasForeignKey("PredmetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Studentsky_spravce.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Predmet");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Studentsky_spravce.Models.Student", b =>
                {
                    b.HasOne("Studentsky_spravce.Models.Trida", "Trida")
                        .WithMany("Studente")
                        .HasForeignKey("TridaId");

                    b.Navigation("Trida");
                });

            modelBuilder.Entity("Studentsky_spravce.Models.Rozvrh", b =>
                {
                    b.Navigation("Hodiny");
                });

            modelBuilder.Entity("Studentsky_spravce.Models.Trida", b =>
                {
                    b.Navigation("Studente");
                });
#pragma warning restore 612, 618
        }
    }
}
